### ISSUE TITLE
Error: Command failed when running build

### ISSUE THREAD

**Issue by schalkneethling** [ThePacielloGroup/cupper#33]
When explicitly running `npm run build` or, when it is run as a pre-commit hook, I get the following error in Terminal:

```
> MDN-Fiori@0.1.0 build /Users/espressive/repos/mdn-fiori
> node lib/build.js

Building...
{ Error: Command failed: rm -rfv /Users/user/repos/mdn-fiori/docs/* && hugo && sw-precache --root=docs && git add -A

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:541:12)
  killed: false,
  code: 255,
  signal: null,
  cmd: 'rm -rfv /Users/user/repos/mdn-fiori/docs/* && hugo && sw-precache --root=docs && git add -A' }
```

You can see the repo in question at https://github.com/mdn/mdn-fiori

Thanks!

**Comment by paulmsmith** [comment]
@schalkneethling That looks like you don't have the code in a git repository. If you go to the root directory/folder and run `git init` you can answer some basic questions to set-up git on your local computer. Do that and then run the command again.

**Comment by schalkneethling** [comment]
@paulmsmith Thanks, but it is definitely a git repository:

<img width="751" alt="screen shot 2018-04-28 at 12 52 54" src="https://user-images.githubusercontent.com/10350960/39395768-261ee4dc-4ae3-11e8-9149-3e11ab612beb.png">

You can also see the repo in question at https://github.com/mdn/mdn-fiori

Thanks!
