### ISSUE TITLE
localhost server doesn't work with Hugo (v0.40.2)

### ISSUE THREAD

**Issue by mathalete** [ThePacielloGroup/cupper#35]
After installing latest build of Hugo (v0.40.2) using home-brew noticed that Cupper doesn't serve locally eg: on localhost:1313

I'm on Mac High Sierra 10.13.4 (17E202).

Error log below for reference.

***
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'serve' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle cupper@0.1.0~preserve: cupper@0.1.0
6 info lifecycle cupper@0.1.0~serve: cupper@0.1.0
7 verbose lifecycle cupper@0.1.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle cupper@0.1.0~serve: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/[retracted]/Desktop/Desktop/TPG/Cupper/cupper/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public
9 verbose lifecycle cupper@0.1.0~serve: CWD: /Users/[retracted]/Desktop/Desktop/TPG/Cupper/cupper
10 silly lifecycle cupper@0.1.0~serve: Args: [ '-c', 'hugo server --baseURL http://localhost:1313' ]
11 silly lifecycle cupper@0.1.0~serve: Returned: code: 255  signal: null
12 info lifecycle cupper@0.1.0~serve: Failed to exec serve script
13 verbose stack Error: cupper@0.1.0 serve: `hugo server --baseURL http://localhost:1313`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cupper@0.1.0
15 verbose cwd /Users/peterheery/Desktop/Desktop/TPG/Cupper/cupper
16 verbose Darwin 17.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
18 verbose node v8.10.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 255
22 error cupper@0.1.0 serve: `hugo server --baseURL http://localhost:1313`
22 error Exit status 255
23 error Failed at the cupper@0.1.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ] 
***

**Comment by poorgeek** [comment]
Still not sure what's causing the problem, but deleting `README_BLANK.md` in `themes/cupper/data` at least allowed the server to run.

**Comment by Heydon** [comment]
@poorgeek Hi, just seen this. Thanks for taking a look. README_BLANK.md is needed for the clean command. Is the issue that the default port is different in the new version of Hugo?
